# Generated by Django 6.0.6 on 2026-06-09 20:52

import django.db.models.deletion
import registry.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('caregiver', 'Caregiver'), ('client', 'Client')], max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=registry.models.default_invite_expiration)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_zip_code', models.CharField(max_length=10)),
                ('willing_to_work_cities', models.JSONField(blank=True, default=list)),
                ('transportation', models.JSONField(blank=True, default=list)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('hours_looking_for', models.CharField(choices=[('all_welcome', 'All are welcome'), ('few_hours', 'Just a few hours'), ('part_time', 'Part-Time'), ('full_time', 'Full Time'), ('live_in', 'Live-In'), ('flexible', 'Flexible')], max_length=50)),
                ('certified_ihss_worker', models.BooleanField(default=False)),
                ('additional_certifications', models.TextField(blank=True)),
                ('experience_with', models.JSONField(blank=True, default=list)),
                ('languages_spoken', models.JSONField(blank=True, default=list)),
                ('pathogen_protocols', models.JSONField(blank=True, default=list)),
                ('rate', models.CharField(choices=[('17_20', '$17-$20/hr'), ('20_25', '$20-$25/hr'), ('25_30', '$25-$30/hr'), ('30_50', '$30-$50/hr'), ('50_plus', '$50+/hr')], max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('wants_training_updates', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_zip_code', models.CharField(max_length=10)),
                ('attendant_care_programs', models.JSONField(blank=True, default=list)),
                ('languages_preferred', models.JSONField(blank=True, default=list)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('schedule_flexibility', models.BooleanField(default=False)),
                ('hours_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('care_needs', models.JSONField(blank=True, default=list)),
                ('additional_care_needs', models.TextField(blank=True)),
                ('preferences', models.TextField(blank=True)),
                ('pathogen_protocol_preferences', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationCaregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_caregivers', to='accounts.userprofile')),
                ('caregiver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_relationships', to='registry.caregiverprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_relationships', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='registry_or_organiz_431c6b_idx'), models.Index(fields=['caregiver_profile', 'status'], name='registry_or_caregiv_f43dc9_idx')],
                'unique_together': {('organization', 'caregiver_profile')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clients', to='accounts.userprofile')),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_relationships', to='registry.clientprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_relationships', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='registry_or_organiz_d908c1_idx'), models.Index(fields=['client_profile', 'status'], name='registry_or_client__1c0f29_idx')],
                'unique_together': {('organization', 'client_profile')},
            },
        ),
    ]
