# Generated by Django 6.0.5 on 2026-06-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='attendant_care_programs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
