# Generated by Django 6.0.6 on 2026-06-09 22:31

import django.db.models.deletion
import registry.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_to_clients', models.CharField(help_text='E.g., Family member, Agency representative, Friend, etc.', max_length=100)),
                ('credentials', models.TextField(blank=True, help_text='Professional credentials or qualifications')),
                ('certifications', models.TextField(blank=True, help_text='Relevant certifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_coordinator_profile', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Support Coordinator Profile',
                'verbose_name_plural': 'Support Coordinator Profiles',
            },
        ),
        migrations.CreateModel(
            name='CoordinatorInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the invited coordinator', max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for the invitation link', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=registry.models.default_invite_expiration, help_text='Invitation expires 7 days after creation')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_invites', to='registry.clientprofile')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_invites_created', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Coordinator Invitation',
                'verbose_name_plural': 'Coordinator Invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='registry_co_token_b773b9_idx'), models.Index(fields=['client_profile', 'email'], name='registry_co_client__b1e560_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_profile', models.BooleanField(default=False, help_text="Can the coordinator edit the client's profile?")),
                ('can_approve_caregivers', models.BooleanField(default=False, help_text='Can the coordinator approve/reject caregiver matches?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', help_text='Status of the coordinator relationship', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_relationships', to='registry.clientprofile')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_invitations_sent', to='accounts.userprofile')),
                ('coordinator_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_relationships', to='registry.supportcoordinatorprofile')),
            ],
            options={
                'verbose_name': 'Client-Coordinator Relationship',
                'verbose_name_plural': 'Client-Coordinator Relationships',
                'indexes': [models.Index(fields=['client_profile', 'status'], name='registry_cl_client__d1436c_idx'), models.Index(fields=['coordinator_profile', 'status'], name='registry_cl_coordin_6b0168_idx')],
                'unique_together': {('client_profile', 'coordinator_profile')},
            },
        ),
    ]
