# Generated by Django 6.0.5 on 2026-06-09 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_zip_code', models.CharField(max_length=10)),
                ('willing_to_work_cities', models.JSONField(blank=True, default=list)),
                ('transportation', models.JSONField(blank=True, default=list)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('hours_looking_for', models.CharField(choices=[('all_welcome', 'All are welcome'), ('few_hours', 'Just a few hours'), ('part_time', 'Part-Time'), ('full_time', 'Full Time'), ('live_in', 'Live-In'), ('flexible', 'Flexible')], max_length=50)),
                ('certified_ihss_worker', models.BooleanField(default=False)),
                ('additional_certifications', models.TextField(blank=True)),
                ('experience_with', models.JSONField(blank=True, default=list)),
                ('languages_spoken', models.JSONField(blank=True, default=list)),
                ('pathogen_protocols', models.JSONField(blank=True, default=list)),
                ('rate', models.CharField(choices=[('17_20', '$17-$20/hr'), ('20_25', '$20-$25/hr'), ('25_30', '$25-$30/hr'), ('30_50', '$30-$50/hr'), ('50_plus', '$50+/hr')], max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('wants_training_updates', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('base_zip_code', models.CharField(max_length=10)),
                ('attendant_care_programs', models.JSONField(blank=True, default=list)),
                ('languages_preferred', models.JSONField(blank=True, default=list)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('schedule_flexibility', models.BooleanField(default=False)),
                ('hours_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('care_needs', models.JSONField(blank=True, default=list)),
                ('additional_care_needs', models.TextField(blank=True)),
                ('preferences', models.TextField(blank=True)),
                ('pathogen_protocol_preferences', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
