# Generated by Django 6.0.5 on 2026-06-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_caregiverprofile_attendant_care_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='desired_hours_per_week',
            field=models.PositiveIntegerField(blank=True, help_text='Desired number of work hours per week', null=True),
        ),
    ]
