# Generated by Django 6.0.6 on 2026-06-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_supportcoordinatorprofile_coordinatorinvite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='preferences',
        ),
    ]
