# Generated by Django 6.0.5 on 2026-07-08 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_email_remove_userprofile_name'),
        ('matching', '0002_seed_default_tags'),
        ('organizations', '0001_initial'),
        ('registry', '0003_caregiverprofile_desired_hours_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[('caregiver', 'Careworker'), ('client', 'Client')], max_length=20),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partially_approved', 'Partially Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the client')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='registry.caregiverprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='registry.clientprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to='accounts.userprofile')),
                ('match', models.ForeignKey(blank=True, help_text='The active match this schedule is attached to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='matching.match')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='organizations.organization')),
                ('support_person', models.ForeignKey(blank=True, help_text='Optional support person/coordinator who also approves this schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='registry.supportcoordinatorprofile')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week for this recurring slot', max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('caregiver_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('caregiver_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('caregiver_notes', models.TextField(blank=True, help_text='Optional note from caregiver when rejecting')),
                ('support_person_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('support_person_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('support_person_notes', models.TextField(blank=True, help_text='Optional note from support person when rejecting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='registry.schedule')),
            ],
            options={
                'verbose_name': 'Schedule Entry',
                'verbose_name_plural': 'Schedule Entries',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['organization', 'status'], name='registry_sc_organiz_59e2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['client', 'status'], name='registry_sc_client__8f65f3_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['caregiver', 'status'], name='registry_sc_caregiv_7af28c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleentry',
            unique_together={('schedule', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
