# Generated by Django 6.0.5 on 2026-07-10 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_email_remove_userprofile_name'),
        ('registry', '0005_schedule_recurrence_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_role', models.CharField(choices=[('client', 'Client'), ('caregiver', 'Caregiver')], help_text='Whether the rater is the client or careworker in this schedule.', max_length=10)),
                ('rating_date', models.DateField(help_text='The specific calendar date this session occurred on.')),
                ('care_fit_respect', models.PositiveSmallIntegerField(help_text='1–10. Care Fit & Respect: mutual understanding of needs, preferences, and boundaries.')),
                ('communication_coordination', models.PositiveSmallIntegerField(help_text='1–10. Communication & Coordination: clarity, responsiveness, and problem-solving.')),
                ('reliability_consistency', models.PositiveSmallIntegerField(help_text='1–10. Reliability & Consistency: attendance, punctuality, and follow-through.')),
                ('workload_support_balance', models.PositiveSmallIntegerField(help_text='1–10. Workload & Support Balance: sustainability and appropriate support for all parties.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes or context for this rating.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rater_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_ratings_given', to='accounts.userprofile')),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='registry.scheduleentry')),
            ],
            options={
                'verbose_name': 'Schedule Entry Rating',
                'verbose_name_plural': 'Schedule Entry Ratings',
                'ordering': ['-rating_date', '-created_at'],
                'unique_together': {('schedule_entry', 'rater_profile', 'rating_date')},
            },
        ),
    ]
