# Generated by Django 6.0.5 on 2026-06-10 14:29

import django.db.models.deletion
import organizations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to='accounts.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationStaffInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=organizations.models.default_staff_invite_expiration)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invites', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('can_view_dashboard', models.BooleanField(default=True)),
                ('can_approve_applications', models.BooleanField(default=False)),
                ('can_invite_staff', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_invites_sent', to='accounts.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='organizations.organization')),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_relationships', to='accounts.staffprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'role', 'status'], name='organizatio_organiz_9cab11_idx'), models.Index(fields=['staff_profile', 'status'], name='organizatio_staff_p_7ffc53_idx')],
                'unique_together': {('organization', 'staff_profile')},
            },
        ),
    ]
