# Generated by Django 6.0.5 on 2026-06-17 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
        ('registry', '0002_caregiverprofile_attendant_care_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text="Lowercase slug, e.g. 'wheelchair' or 'fragrance-free'", max_length=100, unique=True)),
                ('label', models.CharField(help_text='Human-readable label shown in the UI', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this tag covers')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tags are hidden from selection UIs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by', models.CharField(choices=[('caregiver', 'Caregiver'), ('client', 'Client'), ('staff', 'Staff'), ('ai', 'AI')], help_text='Which party initiated the match', max_length=20)),
                ('caregiver_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('client_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('staff_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('match_score', models.FloatField(blank=True, help_text='Numeric compatibility score (0–100)', null=True)),
                ('match_details', models.JSONField(blank=True, default=dict, help_text='Structured breakdown of match factors: tag overlap, availability, location, transportation, etc.')),
                ('ai_reasoning', models.TextField(blank=True, help_text='Human-readable explanation of match quality from AI or local scorer')),
                ('notes', models.TextField(blank=True, help_text='Optional staff notes about this match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='registry.caregiverprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='registry.clientprofile')),
                ('initiated_by_user', models.ForeignKey(blank=True, help_text='The specific user who created this match record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_matches', to='accounts.userprofile')),
                ('organization', models.ForeignKey(help_text='The organization under which this match is proposed', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='organizations.organization')),
                ('selected_tags', models.ManyToManyField(blank=True, help_text='Tags selected when this match was created', related_name='matches', to='matching.tag')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('match_request', 'Match Request'), ('match_approved', 'Match Approved'), ('match_declined', 'Match Declined'), ('match_active', 'Match Active'), ('match_cancelled', 'Match Cancelled'), ('general', 'General')], default='general', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='matching.match')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='matching_no_recipie_c5dd42_idx'), models.Index(fields=['recipient', 'created_at'], name='matching_no_recipie_903475_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['organization', 'status'], name='matching_ma_organiz_c0d8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['caregiver', 'status'], name='matching_ma_caregiv_41b30b_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['client', 'status'], name='matching_ma_client__d758f7_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['caregiver', 'client', 'status'], name='matching_ma_caregiv_7356dd_idx'),
        ),
    ]
